name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Agar gradlew missing ho, to system Gradle install karo
      - name: Install Gradle if missing
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "gradlew not found, installing Gradle..."
            sudo apt-get update
            sudo apt-get install -y gradle
          else
            chmod +x ./gradlew
          fi

      - name: Build with Gradle
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
